#Load Data

In [1]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"qorxmazahbazl","key":"015cc426ef78862a59fe7291a6ec1f02"}'}

In [2]:
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [3]:
#!/bin/bash
!kaggle datasets download arunjathari/bostonhousepricedata

Dataset URL: https://www.kaggle.com/datasets/arunjathari/bostonhousepricedata
License(s): CC0-1.0
Downloading bostonhousepricedata.zip to /content
100% 12.3k/12.3k [00:00<00:00, 32.7MB/s]

In [4]:
!unzip /content/bostonhousepricedata.zip

Archive:  /content/bostonhousepricedata.zip
  inflating: Boston-house-price-data.csv

In [5]:
import pandas as pd
df = pd.read_csv('/content/Boston-house-price-data.csv')
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

#Statistics Results

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [7]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [9]:
df['CHAS'].value_counts()

CHAS
0    471
1     35
Name: count, dtype: int64

In [11]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [14]:
dupl = df.duplicated().sum()
if dupl > 0:
    df = df.drop_duplicates().reset_index(drop = True)

df.shape

(506, 14)

In [40]:
df['CHAS'] = df['CHAS'].astype(str)

In [41]:
df['RAD'] = df['RAD'].astype(str)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    object
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    object
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), object(2)
memory usage: 55.5+ KB

In [51]:
cat_col = df.select_dtypes(include = 'object').columns

In [52]:
cat_col

Index(['CHAS', 'RAD'], dtype='object')

CHAS
0    471
1     35
Name: count, dtype: int64
RAD
24    132
5     115
4     110
3      38
6      26
8      24
2      24
1      20
7      17
Name: count, dtype: int64

In [54]:
num_col = df.select_dtypes(exclude = 'object').columns

In [55]:
num_col

Index(['CRIM', 'ZN', 'INDUS', 'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'B',
       'LSTAT', 'MEDV'],
      dtype='object')

In [71]:
for col in num_col:
    z_scores = (df[col] - df[col].mean()) / df[col].std()

    z_counts = (z_scores.abs() > 3).sum()

    print(f'Column {col}: {z_counts} outliers (Z-score > 3)')

Column CRIM: 8 outliers (Z-score > 3)
Column ZN: 14 outliers (Z-score > 3)
Column INDUS: 0 outliers (Z-score > 3)
Column NOX: 0 outliers (Z-score > 3)
Column RM: 8 outliers (Z-score > 3)
Column AGE: 0 outliers (Z-score > 3)
Column DIS: 5 outliers (Z-score > 3)
Column TAX: 0 outliers (Z-score > 3)
Column PTRATIO: 0 outliers (Z-score > 3)
Column B: 25 outliers (Z-score > 3)
Column LSTAT: 5 outliers (Z-score > 3)
Column MEDV: 0 outliers (Z-score > 3)

#Data Analysis with Pandas

In [75]:
corr = df.corr(method = 'spearman').round(3)
corr

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
CRIM,1.000,-0.572,0.736,0.042,0.821,-0.309,0.704,-0.745,0.728,0.729,0.465,-0.361,0.635,-0.559
ZN,-0.572,1.000,-0.643,-0.042,-0.635,0.361,-0.544,0.615,-0.279,-0.371,-0.448,0.163,-0.490,0.438
INDUS,0.736,-0.643,1.000,0.090,0.791,-0.415,0.679,-0.757,0.456,0.664,0.434,-0.286,0.639,-0.578
CHAS,0.042,-0.042,0.090,1.000,0.068,0.059,0.068,-0.080,0.025,-0.044,-0.136,-0.040,-0.051,0.141
NOX,0.821,-0.635,0.791,0.068,1.000,-0.310,0.795,-0.880,0.586,0.650,0.391,-0.297,0.637,-0.563
RM,-0.309,0.361,-0.415,0.059,-0.310,1.000,-0.278,0.263,-0.107,-0.272,-0.313,0.054,-0.641,0.634
AGE,0.704,-0.544,0.679,0.068,0.795,-0.278,1.000,-0.802,0.418,0.526,0.355,-0.228,0.657,-0.548
DIS,-0.745,0.615,-0.757,-0.080,-0.880,0.263,-0.802,1.000,-0.496,-0.574,-0.322,0.250,-0.564,0.446
RAD,0.728,-0.279,0.456,0.025,0.586,-0.107,0.418,-0.496,1.000,0.705,0.318,-0.283,0.394,-0.347
TAX,0.729,-0.371,0.664,-0.044,0.650,-0.272,0.526,-0.574,0.705,1.000,0.453,-0.330,0.534,-0.562
PTRATIO,0.465,-0.448,0.434,-0.136,0.391,-0.313,0.355,-0.322,0.318,0.453,1.000,-0.072,0.467,-0.556
B,-0.361,0.163,-0.286,-0.040,-0.297,0.054,-0.228,0.250,-0.283,-0.330,-0.072,1.000,-0.211,0.186
LSTAT,0.635,-0.490,0.639,-0.051,0.637,-0.641,0.657,-0.564,0.394,0.534,0.467,-0.211,1.000,-0.853
MEDV,-0.559,0.438,-0.578,0.141,-0.563,0.634,-0.548,0.446,-0.347,-0.562,-0.556,0.186,-0.853,1.000

In [80]:
medv_corr = corr['MEDV'].drop('MEDV').sort_values(key = abs, ascending = False)
medv_corr

LSTAT     -0.853
RM         0.634
INDUS     -0.578
NOX       -0.563
TAX       -0.562
CRIM      -0.559
PTRATIO   -0.556
AGE       -0.548
DIS        0.446
ZN         0.438
RAD       -0.347
B          0.186
CHAS       0.141
Name: MEDV, dtype: float64

#FEATURE ENGINEERING

In [81]:
df['TAX_PER_ROOM'] = df['TAX'] / df['RM']
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,TAX_PER_ROOM
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0,45.019011
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,37.688834
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,33.681280
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,31.723350
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,31.061984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4,41.407553
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6,44.607843
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9,39.134174
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0,40.182514
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9,45.273632

In [85]:
df['CRIM_PER_ZN'] = df['CRIM'] / (df['ZN'] + 1)
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,TAX_PER_ROOM,CRIM_PER_ZN
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0,45.019011,0.000333
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,37.688834,0.027310
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,33.681280,0.027290
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,31.723350,0.032370
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,31.061984,0.069050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4,41.407553,0.062630
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6,44.607843,0.045270
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9,39.134174,0.060760
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0,40.182514,0.109590
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9,45.273632,0.047410

In [86]:
import numpy as np

df['LOG_CRIM'] = np.log1p(df['CRIM'])
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,TAX_PER_ROOM,CRIM_PER_ZN,LOG_CRIM
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0,45.019011,0.000333,0.006300
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,37.688834,0.027310,0.026944
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,33.681280,0.027290,0.026924
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,31.723350,0.032370,0.031857
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,31.061984,0.069050,0.066770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4,41.407553,0.062630,0.060747
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6,44.607843,0.045270,0.044275
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9,39.134174,0.060760,0.058986
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0,40.182514,0.109590,0.103991
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9,45.273632,0.047410,0.046320

In [87]:
df['LOG_ZN'] = np.log1p(df['ZN'])
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,TAX_PER_ROOM,CRIM_PER_ZN,LOG_CRIM,LOG_ZN
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0,45.019011,0.000333,0.006300,2.944439
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,37.688834,0.027310,0.026944,0.000000
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,33.681280,0.027290,0.026924,0.000000
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,31.723350,0.032370,0.031857,0.000000
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,31.061984,0.069050,0.066770,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4,41.407553,0.062630,0.060747,0.000000
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6,44.607843,0.045270,0.044275,0.000000
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9,39.134174,0.060760,0.058986,0.000000
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0,40.182514,0.109590,0.103991,0.000000
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9,45.273632,0.047410,0.046320,0.000000

In [91]:
df['HIGH CRIM'] = (df['CRIM'] > df['CRIM'].quantile(0.75)).astype(int)
df[df['HIGH CRIM'] > 0]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,TAX_PER_ROOM,CRIM_PER_ZN,LOG_CRIM,LOG_ZN,HIGH CRIM
143,4.09740,0.0,19.58,0,0.871,5.468,100.0,1.4118,5,403.0,14.7,396.90,26.42,15.6,73.701536,4.09740,1.628731,0.0,1
356,8.98296,0.0,18.10,1,0.770,6.212,97.4,2.1222,24,666.0,20.2,377.73,17.60,17.8,107.211848,8.98296,2.300880,0.0,1
357,3.84970,0.0,18.10,1,0.770,6.395,91.0,2.5052,24,666.0,20.2,391.34,13.27,21.7,104.143862,3.84970,1.578917,0.0,1
358,5.20177,0.0,18.10,1,0.770,6.127,83.4,2.7227,24,666.0,20.2,395.43,11.48,22.7,108.699200,5.20177,1.824835,0.0,1
359,4.26131,0.0,18.10,0,0.770,6.112,81.3,2.5091,24,666.0,20.2,390.74,12.67,22.6,108.965969,4.26131,1.660380,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,5.82401,0.0,18.10,0,0.532,6.242,64.7,3.4242,24,666.0,20.2,396.90,10.74,23.0,106.696572,5.82401,1.920447,0.0,1
481,5.70818,0.0,18.10,0,0.532,6.750,74.9,3.3317,24,666.0,20.2,393.07,7.74,23.7,98.666667,5.70818,1.903328,0.0,1
482,5.73116,0.0,18.10,0,0.532,7.061,77.0,3.4106,24,666.0,20.2,395.28,7.01,25.0,94.320918,5.73116,1.906747,0.0,1
486,5.69175,0.0,18.10,0,0.583,6.114,79.8,3.5459,24,666.0,20.2,392.68,14.98,19.1,108.930324,5.69175,1.900875,0.0,1
487,4.83567,0.0,18.10,0,0.583,5.905,53.2,3.1523,24,666.0,20.2,388.22,11.45,20.6,112.785775,4.83567,1.763989,0.0,1

In [92]:
new_corr = df.corr(method = 'spearman').round(3)

In [93]:
new_corr

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,TAX_PER_ROOM,CRIM_PER_ZN,LOG_CRIM,LOG_ZN,HIGH CRIM
CRIM,1.000,-0.572,0.736,0.042,0.821,-0.309,0.704,-0.745,0.728,0.729,0.465,-0.361,0.635,-0.559,0.731,0.941,1.000,-0.572,0.751
ZN,-0.572,1.000,-0.643,-0.042,-0.635,0.361,-0.544,0.615,-0.279,-0.371,-0.448,0.163,-0.490,0.438,-0.414,-0.772,-0.572,1.000,-0.342
INDUS,0.736,-0.643,1.000,0.090,0.791,-0.415,0.679,-0.757,0.456,0.664,0.434,-0.286,0.639,-0.578,0.688,0.789,0.736,-0.643,0.522
CHAS,0.042,-0.042,0.090,1.000,0.068,0.059,0.068,-0.080,0.025,-0.044,-0.136,-0.040,-0.051,0.141,-0.053,0.040,0.042,-0.042,-0.032
NOX,0.821,-0.635,0.791,0.068,1.000,-0.310,0.795,-0.880,0.586,0.650,0.391,-0.297,0.637,-0.563,0.661,0.833,0.821,-0.635,0.636
RM,-0.309,0.361,-0.415,0.059,-0.310,1.000,-0.278,0.263,-0.107,-0.272,-0.313,0.054,-0.641,0.634,-0.498,-0.359,-0.309,0.361,-0.168
AGE,0.704,-0.544,0.679,0.068,0.795,-0.278,1.000,-0.802,0.418,0.526,0.355,-0.228,0.657,-0.548,0.535,0.714,0.704,-0.544,0.503
DIS,-0.745,0.615,-0.757,-0.080,-0.880,0.263,-0.802,1.000,-0.496,-0.574,-0.322,0.250,-0.564,0.446,-0.584,-0.779,-0.745,0.615,-0.579
RAD,0.728,-0.279,0.456,0.025,0.586,-0.107,0.418,-0.496,1.000,0.705,0.318,-0.283,0.394,-0.347,0.670,0.662,0.728,-0.279,0.751
TAX,0.729,-0.371,0.664,-0.044,0.650,-0.272,0.526,-0.574,0.705,1.000,0.453,-0.330,0.534,-0.562,0.960,0.722,0.729,-0.371,0.725
PTRATIO,0.465,-0.448,0.434,-0.136,0.391,-0.313,0.355,-0.322,0.318,0.453,1.000,-0.072,0.467,-0.556,0.500,0.537,0.465,-0.448,0.498
B,-0.361,0.163,-0.286,-0.040,-0.297,0.054,-0.228,0.250,-0.283,-0.330,-0.072,1.000,-0.211,0.186,-0.297,-0.329,-0.361,0.163,-0.260
LSTAT,0.635,-0.490,0.639,-0.051,0.637,-0.641,0.657,-0.564,0.394,0.534,0.467,-0.211,1.000,-0.853,0.645,0.657,0.635,-0.490,0.510
MEDV,-0.559,0.438,-0.578,0.141,-0.563,0.634,-0.548,0.446,-0.347,-0.562,-0.556,0.186,-0.853,1.000,-0.669,-0.604,-0.559,0.438,-0.497
TAX_PER_ROOM,0.731,-0.414,0.688,-0.053,0.661,-0.498,0.535,-0.584,0.670,0.960,0.500,-0.297,0.645,-0.669,1.000,0.739,0.731,-0.414,0.723
CRIM_PER_ZN,0.941,-0.772,0.789,0.040,0.833,-0.359,0.714,-0.779,0.662,0.722,0.537,-0.329,0.657,-0.604,0.739,1.000,0.941,-0.772,0.751
LOG_CRIM,1.000,-0.572,0.736,0.042,0.821,-0.309,0.704,-0.745,0.728,0.729,0.465,-0.361,0.635,-0.559,0.731,0.941,1.000,-0.572,0.751
LOG_ZN,-0.572,1.000,-0.643,-0.042,-0.635,0.361,-0.544,0.615,-0.279,-0.371,-0.448,0.163,-0.490,0.438,-0.414,-0.772,-0.572,1.000,-0.342
HIGH CRIM,0.751,-0.342,0.522,-0.032,0.636,-0.168,0.503,-0.579,0.751,0.725,0.498,-0.260,0.510,-0.497,0.723,0.751,0.751,-0.342,1.000

In [94]:
!wget https://github.com/Rstam59/TaskDataRepoForStudents/blob/main/world_population.csv

--2026-05-20 13:08:35--  https://github.com/Rstam59/TaskDataRepoForStudents/blob/main/world_population.csv
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘world_population.csv’

world_population.cs     [ <=>                ] 407.37K  --.-KB/s    in 0.009s

2026-05-20 13:08:36 (42.9 MB/s) - ‘world_population.csv’ saved [417150]

In [96]:
!wget -O /content/world_population.csv https://github.com/Rstam59/TaskDataRepoForStudents/raw/main/world_population.csv
df_world_population = pd.read_csv('/content/world_population.csv')

--2026-05-20 13:09:41--  https://github.com/Rstam59/TaskDataRepoForStudents/raw/main/world_population.csv
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Rstam59/TaskDataRepoForStudents/main/world_population.csv [following]
--2026-05-20 13:09:41--  https://raw.githubusercontent.com/Rstam59/TaskDataRepoForStudents/main/world_population.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28923 (28K) [text/plain]
Saving to: ‘/content/world_population.csv’

/content/world_popu 100%[===================>]  28.25K  --.-KB/s    in 0s

2026-05-20 13:09:42 (118 MB/s) - ‘/content/world_population.csv’ saved [28923/28923]

In [97]:
df_world_population

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20